/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import javax.swing.JOptionPane;

/**
 *
 * @author EAV
 */
public class Comentarios extends javax.swing.JFrame {

    /**
     * Creates new form Comentarios
     */
    public Comentarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        Datos sugs = new Datos();
        sugerencias.setText(sugs.coments);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comentariosenviados = new javax.swing.JLabel();
        salircomentarios = new javax.swing.JButton();
        warning = new javax.swing.JLabel();
        enviados = new javax.swing.JLabel();
        regresarcomentarios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sugerencias = new javax.swing.JTextArea();
        emergente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comentariosenviados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comentariosenviados.setText("Sus comentarios:");

        salircomentarios.setText("Salir");
        salircomentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salircomentariosActionPerformed(evt);
            }
        });

        warning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/warning.png"))); // NOI18N

        enviados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enviados.setText("Se han enviado");

        regresarcomentarios.setText("Regresar");
        regresarcomentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarcomentariosActionPerformed(evt);
            }
        });

        sugerencias.setColumns(20);
        sugerencias.setRows(5);
        jScrollPane1.setViewportView(sugerencias);

        emergente.setText("emergente");
        emergente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(warning)
                        .addGap(37, 37, 37)
                        .addComponent(comentariosenviados, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(enviados)))
                .addContainerGap(176, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(emergente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(regresarcomentarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salircomentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(warning)
                    .addComponent(comentariosenviados, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emergente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enviados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salircomentarios)
                    .addComponent(regresarcomentarios))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salircomentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salircomentariosActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salircomentariosActionPerformed

    private void regresarcomentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarcomentariosActionPerformed
        // TODO add your handling code here:
        Datos dts = new Datos();
        dts.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarcomentariosActionPerformed

    private void emergenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergenteActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, "Ijole");
        int opcionnn=JOptionPane.showConfirmDialog(this, "si o no");
        System.out.println(opcionnn);
    }//GEN-LAST:event_emergenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comentarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comentariosenviados;
    private javax.swing.JButton emergente;
    private javax.swing.JLabel enviados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regresarcomentarios;
    private javax.swing.JButton salircomentarios;
    private javax.swing.JTextArea sugerencias;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
