/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;


import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author EAV
 */
public class Datos extends javax.swing.JFrame {
    
public static ArrayList array= new ArrayList();
public static ArrayList array1= new ArrayList();
public static ArrayList array2= new ArrayList();
public static ArrayList array3= new ArrayList();
public static ArrayList array4= new ArrayList();
public static ArrayList array5= new ArrayList();
public static ArrayList array6= new ArrayList();
public static ArrayList array7= new ArrayList();
public static DefaultListModel modelo = new DefaultListModel();
    /**
     * Creates new form Datos
     */

    
    public Datos() {
        initComponents();
        jPanel1.setBackground(new Color(255,255,255,0));
        user.setLocation(282, 43);
        getContentPane().setComponentZOrder(this.user, 0);
        getContentPane().setComponentZOrder(this.labellist, 1);
        this.setLocationRelativeTo(null);
        
        Ejemplo ejem = new Ejemplo();
        Datospantalla.setModel(modelo);
      
        array1.add("Codigo:");
        array2.add(ejem.codigo);
        array3.add("Contraseña:");
        array4.add(ejem.contraseña);
        array5.add(Ejemplo.getMensaje());
        array6.add("Plantel Seleccionado:");
        array7.add(ejem.plantel);
        modelo.removeAllElements();
        modelo.addElement(array1);
        modelo.addElement(array2);
        modelo.addElement(array3);
        modelo.addElement(array4);
        modelo.addElement(array5);
        modelo.addElement(array6);
        modelo.addElement(array7);
        


 
    }
    public static String coments="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labellist = new javax.swing.JLabel();
        comentarios = new javax.swing.JLabel();
        enviar = new javax.swing.JButton();
        notas = new javax.swing.JTextField();
        user = new javax.swing.JLabel();
        ingresados = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Datospantalla = new javax.swing.JList<>();
        salirdatos = new javax.swing.JButton();
        Regresardatos = new javax.swing.JButton();
        fondolista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 570));
        getContentPane().setLayout(null);

        labellist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listalabel.png"))); // NOI18N
        labellist.setToolTipText("");

        comentarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comentarios.setText("Envie sus Comentarios");

        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });

        notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notasActionPerformed(evt);
            }
        });

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N

        ingresados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ingresados.setText("Los Datos Ingresados Son:");

        jScrollPane3.setViewportView(Datospantalla);

        salirdatos.setText("Salir");
        salirdatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirdatosActionPerformed(evt);
            }
        });

        Regresardatos.setText("Regresar");
        Regresardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresardatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(comentarios))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(ingresados))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(user)
                        .addGap(112, 112, 112)
                        .addComponent(labellist)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(notas, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Regresardatos)
                .addGap(250, 250, 250)
                .addComponent(enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(salirdatos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addComponent(user)
                        .addGap(455, 455, 455))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labellist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ingresados)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(comentarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(notas, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enviar)
                            .addComponent(salirdatos)
                            .addComponent(Regresardatos))
                        .addGap(52, 52, 52))))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 570);

        fondolista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondolista.jpg"))); // NOI18N
        getContentPane().add(fondolista);
        fondolista.setBounds(0, 0, 800, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        // TODO add your handling code here:
        coments=notas.getText();
        Comentarios cmt = new Comentarios();
        cmt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_enviarActionPerformed

    private void notasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notasActionPerformed

    private void salirdatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirdatosActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirdatosActionPerformed

    private void RegresardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresardatosActionPerformed
        // TODO add your handling code here:
        Ejemplo ejem = new Ejemplo();
        ejem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegresardatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Datospantalla;
    private javax.swing.JButton Regresardatos;
    private javax.swing.JLabel comentarios;
    private javax.swing.JButton enviar;
    private javax.swing.JLabel fondolista;
    private javax.swing.JLabel ingresados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labellist;
    private javax.swing.JTextField notas;
    private javax.swing.JButton salirdatos;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
